networks:
  local.cst:

services:

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
#    expose:
#      - '6379'
    volumes:
      - redis_data:/data
    networks:
      - local.cst
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    container_name: app
    image: parser
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    networks:
      - local.cst
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../src:/app/
    environment:
      - DEBUG=${DEBUG}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TIME_ZONE=${TIME_ZONE}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

volumes:
  redis_data:
